### ISSUE TITLE
pokedex bug

### ISSUE THREAD

**Issue by ChoriPunk69** [flaree/pokecord-red#12]
if i evolved a pokemon, the pre evolucion doesn't record in the pokedex or if a evolved a pokemon the evolution doesn't record in the pokedex

https://prnt.sc/u53w3i

torchic was my starter pokemon

**Comment by flaree** [comment]
Sorry for taking my time with this issue, just have had no motivation as of right now. lll take time over the weekend to address this.

**Comment by flaree** [comment]
Sorry for late response, should be added now.
