### ISSUE TITLE
Pokecord features and ideas update 

### ISSUE THREAD

**Issue by AfterWorld** [flaree/pokecord-red#28]
So as the title say, Features and Ideas. I know you can catch fishes and such. But since fishing is in the bot, allow users to catch certain items depending on the rod. To help them improve their pokes maybe ? 

Only idea I have for now 😂
-UltPanda

**Comment by flaree** [comment]
This was the intention when fish was a private cog back on Pikachu but as
its public now it won't be in it. Its still in consideration for bring a
private feature. Items will all be bought via a store or trading
