### ISSUE TITLE
Suggestion: Command to disable in some channels

### ISSUE THREAD

**Issue by sleepymanakete** [flaree/pokecord-red#6]
Hi! As the tile states, I like to suggest a command where you can turn off the spawns in some channels instead of setting it where pokemon spawn in one channel.
Example: `[p]pokecordset spawndisable #memes`

Thank you!

**Comment by flaree** [comment]
I've added this to the in-progress section in the project, I'll be reworking the active channel system to utilize both a whitelist/blacklist as suggested beforehand. I won't get around to it until the weekend atleast though.

**Comment by sleepymanakete** [comment]
Thank you!

**Comment by flaree** [comment]
(forgot to say this was done)

**Comment by sleepymanakete** [comment]
thx!
